import { useState } from 'react';
import { Sparkles, User, CalendarClock } from 'lucide-react';
import type { ActionItem } from '@collabboard/shared';
import { aiApi } from '../../api/boardExtras';
import { Button } from '../ui/Button';
import { useToast } from '../../hooks/useToast';

interface ActionItemsPanelProps {
  boardId: string;
  /** Surfaces the latest items upward so the board can embed them in the PDF. */
  onItemsChange?: (items: ActionItem[]) => void;
}

function confidenceTone(c: number): string {
  if (c >= 0.75) return 'bg-emerald-500';
  if (c >= 0.5) return 'bg-amber-500';
  return 'bg-slate-400';
}

/** Extracts action items from the live notes via the AI service. */
export function ActionItemsPanel({ boardId, onItemsChange }: ActionItemsPanelProps) {
  const [items, setItems] = useState<ActionItem[]>([]);
  const [model, setModel] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [ran, setRan] = useState(false);
  const toast = useToast();

  const generate = async () => {
    setLoading(true);
    try {
      const res = await aiApi.actionItems(boardId);
      setItems(res.items);
      setModel(res.model);
      setRan(true);
      onItemsChange?.(res.items);
    } catch {
      toast('Could not generate action items', 'error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="border-t border-slate-200 bg-slate-50/60">
      <div className="flex items-center justify-between px-4 py-2.5">
        <div className="flex items-center gap-1.5 text-sm font-semibold text-slate-700">
          <Sparkles className="h-4 w-4 text-brand-600" />
          Action items
        </div>
        <Button size="sm" variant="secondary" loading={loading} onClick={generate}>
          {ran ? 'Regenerate' : 'Generate'}
        </Button>
      </div>

      <div className="max-h-56 overflow-y-auto px-4 pb-3 scrollbar-thin">
        {!ran && !loading && (
          <p className="py-2 text-xs text-slate-500">
            Turn the meeting notes into a checklist of owners and due dates.
          </p>
        )}
        {ran && items.length === 0 && !loading && (
          <p className="py-2 text-xs text-slate-500">No action items found in the notes yet.</p>
        )}
        <ul className="flex flex-col gap-2">
          {items.map((item) => (
            <li
              key={item.id}
              className="rounded-lg border border-slate-200 bg-white p-2.5 shadow-sm"
            >
              <p className="text-sm text-slate-800">{item.text}</p>
              <div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate-500">
                {item.owner && (
                  <span className="inline-flex items-center gap-1">
                    <User className="h-3 w-3" />
                    {item.owner}
                  </span>
                )}
                {item.due && (
                  <span className="inline-flex items-center gap-1">
                    <CalendarClock className="h-3 w-3" />
                    {item.due}
                  </span>
                )}
                <span className="ml-auto flex items-center gap-1.5">
                  <span className="h-1.5 w-16 overflow-hidden rounded-full bg-slate-200">
                    <span
                      className={`block h-full rounded-full ${confidenceTone(item.confidence)}`}
                      style={{ width: `${Math.round(item.confidence * 100)}%` }}
                    />
                  </span>
                  {Math.round(item.confidence * 100)}%
                </span>
              </div>
            </li>
          ))}
        </ul>
        {model && ran && (
          <p className="mt-2 text-[10px] uppercase tracking-wide text-slate-400">
            Generated by {model}
          </p>
        )}
      </div>
    </div>
  );
}
